### ISSUE TITLE
Colors on previous days change

### ISSUE THREAD

**Issue by raisabelatrix** [Darakah/obsidian-activity-history#19]
Obsidian app and installer version: 0.15.9
OS: Windows 10

I thought I was just remembering it wrongly, but after comparing two screenshots taken on different days, I guess I did not imagine it after all.

Here's the first screenshot, with varied colored squares:

![unknown](https://user-images.githubusercontent.com/82343091/190214385-409f3681-90b7-458f-951e-ff86e86b98e3.png)

And here's the more recent screenshot, with all the squares the same color except for the more recent one (which was yesterday)

![image](https://user-images.githubusercontent.com/82343091/190214510-dea09b0c-3976-4a6a-94f6-28bff40510e4.png)

Not sure if this is a bug or expected behavior. Should my progress color on previous days change when I delete/rename files made on those days?

**Comment by dhatereki** [comment]
Changes to files counts as progress on that day including deletion. So if you delete a lot of files on a specific day and the data deleted is far greater than data created during the previous days it's tracked as a lot of activity. That's why it does that. Colors are all relative.
