### ISSUE TITLE
Don't show any error and any warning with no things changed

### ISSUE THREAD

**Issue by Quorafind** [Darakah/obsidian-activity-history#2]
Had added project(folder) to track list, added five files into this project(folder) and 10 mins gone, nothing changes

**Comment by Darakah** [comment]
- The files you added are MD files?
- If they are MD files, are they all empty? (no a single character)
- After adding the files did you click on another note and then back to the note containing the render block? (so that the element is recreated with the new data)

Did it work?

**Comment by Quorafind** [comment]
@Darakah It works now. So I closed the issue before.
