### ISSUE TITLE
QQ: how to remove projects from trackings

### ISSUE THREAD

**Issue by JasonAn** [Darakah/obsidian-activity-history#5]
same as the title

**Comment by Darakah** [comment]
Hello, 

using the `Stop Tracking Project` from the settings tab. 
Is it not working for you? 

You need to input the same way you did to track the project (i.e. no `/` at the beginning - just copy the name from the `Tracked List` and paste it). 

<img width="1050" alt="Screen Shot 2021-03-04 at 6 56 42 PM" src="https://user-images.githubusercontent.com/29651407/110007813-5d6dd480-7d1b-11eb-8beb-2230dd259922.png">

**Comment by JasonAn** [comment]
This definitely solves my problem, awesome!
